# Generated by Django 5.1 on 2024-10-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField(verbose_name="номер версии")),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="название версии"),
                ),
                (
                    "version_flag",
                    models.BooleanField(default=False, verbose_name="признак версии"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["product", "version_number", "name", "version_flag"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("version_flag", True)),
                        fields=("product", "version_flag"),
                        name="unique_active_version",
                    )
                ],
            },
        ),
    ]
